package academia;
import java.awt.Image;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Insertar_PagoAlum extends javax.swing.JFrame {
    Connection con;
    ImageIcon imagen = new ImageIcon("Icono.gif");
    Image icono = imagen.getImage();
    Calendar c = Calendar.getInstance();
    public Insertar_PagoAlum() {
        initComponents();
        this.setTitle("Insertar Pago de Alumnos");
        this.setIconImage(icono);
        String D=Integer.toString(c.get(Calendar.DATE));
        String M=Integer.toString(c.get(Calendar.MONTH)+1);
        String A=Integer.toString(c.get(Calendar.YEAR));
        txtRFechaP1.setText(D);
        txtRFechaP2.setText(M);
        txtRFechaP3.setText(A);
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:conexion");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR EN LA CONEXION","ERROR",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Insertar_Salones.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxServicio = new javax.swing.JComboBox();
        lblRFechaP = new javax.swing.JLabel();
        txtRFechaP1 = new javax.swing.JTextField();
        txtRFechaP2 = new javax.swing.JTextField();
        txtRFechaP3 = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtPagoAdmi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Costo", "Matricula", "Ciclo", "Fecha Inicio", "Fecha Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicios.getTableHeader().setReorderingAllowed(false);
        tblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServiciosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicios);
        tblServicios.getColumnModel().getColumn(0).setResizable(false);
        tblServicios.getColumnModel().getColumn(1).setResizable(false);
        tblServicios.getColumnModel().getColumn(2).setResizable(false);
        tblServicios.getColumnModel().getColumn(3).setResizable(false);
        tblServicios.getColumnModel().getColumn(4).setResizable(false);
        tblServicios.getColumnModel().getColumn(5).setResizable(false);

        jScrollPane1.setBounds(170, 300, 480, 150);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo Alumno:");
        jLabel1.setBounds(40, 140, 120, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo Servicio:");
        jLabel2.setBounds(40, 240, 130, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Pago a Realizar:");
        jLabel3.setBounds(350, 140, 130, 30);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbxServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Uno", "Academia", "Asesoria" }));
        cbxServicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxServicioItemStateChanged(evt);
            }
        });
        cbxServicio.setBounds(160, 190, 120, 30);
        jLayeredPane1.add(cbxServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblRFechaP.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblRFechaP.setText("Fecha de Pago:");
        lblRFechaP.setBounds(350, 190, 130, 30);
        jLayeredPane1.add(lblRFechaP, javax.swing.JLayeredPane.POPUP_LAYER);

        txtRFechaP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRFechaP1FocusLost(evt);
            }
        });
        txtRFechaP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFechaP1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFechaP1KeyTyped(evt);
            }
        });
        txtRFechaP1.setBounds(470, 190, 40, 30);
        jLayeredPane1.add(txtRFechaP1, javax.swing.JLayeredPane.POPUP_LAYER);

        txtRFechaP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRFechaP2FocusLost(evt);
            }
        });
        txtRFechaP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFechaP2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFechaP2KeyTyped(evt);
            }
        });
        txtRFechaP2.setBounds(520, 190, 40, 30);
        jLayeredPane1.add(txtRFechaP2, javax.swing.JLayeredPane.POPUP_LAYER);

        txtRFechaP3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRFechaP3FocusLost(evt);
            }
        });
        txtRFechaP3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFechaP3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFechaP3KeyTyped(evt);
            }
        });
        txtRFechaP3.setBounds(570, 190, 50, 30);
        jLayeredPane1.add(txtRFechaP3, javax.swing.JLayeredPane.POPUP_LAYER);

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        txtCodigo.setBounds(160, 140, 120, 30);
        jLayeredPane1.add(txtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServicio.setEditable(false);
        txtServicio.setBounds(160, 240, 120, 30);
        jLayeredPane1.add(txtServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPagoAdmi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoAdmiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoAdmiKeyTyped(evt);
            }
        });
        txtPagoAdmi.setBounds(470, 140, 100, 30);
        jLayeredPane1.add(txtPagoAdmi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(50, 310, 80, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(50, 390, 80, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/Fondos/12.jpg"))); // NOI18N
        jLabel4.setBounds(0, 0, 680, 490);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/Insertar_Pago_Alumno.png"))); // NOI18N
        jLabel5.setBounds(100, 20, 570, 80);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRFechaP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRFechaP1FocusLost

        if (recorrer(txtRFechaP2.getText())) {             if (recorrer(txtRFechaP1.getText())) {                 if (recorrer(txtRFechaP3.getText())) {                     if (Integer.parseInt(txtRFechaP1.getText()) < 1 || Integer.parseInt(txtRFechaP1.getText()) > maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))) {                         txtRFechaP1.setText(String.valueOf(maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))));                     }                 }             }         }     }//GEN-LAST:event_txtRFechaP1FocusLost

    private void txtRFechaP1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP1KeyReleased

        if (txtRFechaP1.getText().length() > 1) {             txtRFechaP1.setText(txtRFechaP1.getText().substring(0, 2));             if (recorrer(txtRFechaP2.getText())) {                 if (Integer.parseInt(txtRFechaP1.getText()) < 1 || Integer.parseInt(txtRFechaP1.getText()) > maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))) {                     txtRFechaP1.setText(String.valueOf(maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))));                 }             }         }     }//GEN-LAST:event_txtRFechaP1KeyReleased

    private void txtRFechaP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP1KeyTyped

        bloqueoLetras(evt);     }//GEN-LAST:event_txtRFechaP1KeyTyped

    private void txtRFechaP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRFechaP2FocusLost

        if (recorrer(txtRFechaP2.getText())) {             if (recorrer(txtRFechaP1.getText())) {                 if (recorrer(txtRFechaP3.getText())) {                     if (Integer.parseInt(txtRFechaP1.getText()) < 1 || Integer.parseInt(txtRFechaP1.getText()) > maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))) {                         txtRFechaP1.setText(String.valueOf(maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))));                     }                 }             }         }     }//GEN-LAST:event_txtRFechaP2FocusLost

    private void txtRFechaP2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP2KeyReleased
        if (txtRFechaP2.getText().length() > 1) {
            txtRFechaP2.setText(txtRFechaP2.getText().substring(0, 2));
            if (Integer.parseInt(txtRFechaP2.getText()) < 0 || Integer.parseInt(txtRFechaP2.getText()) > 12) {
                txtRFechaP2.setText("12");
            }
            if (txtRFechaP2.getText().length() == 1) {
                if (Integer.parseInt(txtRFechaP1.getText()) < 1 || Integer.parseInt(txtRFechaP1.getText()) > maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))) {
                    txtRFechaP1.setText(String.valueOf(maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))));
                }
            }
        }
    }//GEN-LAST:event_txtRFechaP2KeyReleased

    private void txtRFechaP2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP2KeyTyped

        bloqueoLetras(evt);     }//GEN-LAST:event_txtRFechaP2KeyTyped

    private void txtRFechaP3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRFechaP3FocusLost

        if (recorrer(txtRFechaP2.getText())) {             if (recorrer(txtRFechaP1.getText())) {                 if (recorrer(txtRFechaP3.getText())) {                     if (Integer.parseInt(txtRFechaP1.getText()) < 1 || Integer.parseInt(txtRFechaP1.getText()) > maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))) {                         txtRFechaP1.setText(String.valueOf(maximodia(Integer.parseInt(txtRFechaP2.getText()) - 1, Integer.parseInt(txtRFechaP3.getText()))));                     }                 }             }         }     }//GEN-LAST:event_txtRFechaP3FocusLost

    private void txtRFechaP3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP3KeyReleased

        if (txtRFechaP3.getText().length() > 3) {             txtRFechaP3.setText(txtRFechaP3.getText().substring(0, 4));         }     }//GEN-LAST:event_txtRFechaP3KeyReleased

    private void txtRFechaP3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFechaP3KeyTyped

        bloqueoLetras(evt);     }//GEN-LAST:event_txtRFechaP3KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxServicioItemStateChanged
        switch(cbxServicio.getSelectedIndex()){
            case 0:limpiar();break;
            case 1:mostrarAcademia();break;
            case 2:mostrarAsesoria();break;
        }
    }//GEN-LAST:event_cbxServicioItemStateChanged

    private void tblServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiciosMousePressed
        if(tblServicios.getSelectedRow()!=-1){
            txtServicio.setText(String.valueOf(tblServicios.getValueAt(tblServicios.getSelectedRow(),0)));
        }
        else{
            JOptionPane.showMessageDialog(this,"Seleccione una fila","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblServiciosMousePressed

    private void txtPagoAdmiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoAdmiKeyTyped
        char caracter = evt.getKeyChar();
        if((caracter < '0') ||(caracter > '9')){
            if(caracter<'.'||caracter>'.'){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtPagoAdmiKeyTyped

    private void txtPagoAdmiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoAdmiKeyReleased
                int c=0;
        String texto=txtPagoAdmi.getText();
        if(texto.length()!=0){
            for(int i=0;i<texto.length();i++){
                if(texto.charAt(i)=='.'){
                    c++;
                }
            }
            if(c==2){
                txtPagoAdmi.setText(texto.substring(0,texto.length()-1));
            }
            if(c>2){
                for(int j=1;j<c;j++){
                    txtPagoAdmi.setText(texto.substring(0,texto.length()-1));
                    texto=txtPagoAdmi.getText();
                }
            }
            if(texto.charAt(0)=='.'){
                txtPagoAdmi.setText("0"+texto);
            }
        }
    }//GEN-LAST:event_txtPagoAdmiKeyReleased

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        if(txtCodigo.getText().length()>6){
             txtCodigo.setText(txtCodigo.getText().substring(0, 6));
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char caracter = evt.getKeyChar();
          if(((caracter < '0') ||(caracter > '9'))&&((caracter < 'a') ||(caracter > 'z'))&&((caracter < 'A') ||(caracter > 'Z'))){
              evt.consume();
          }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(verificar()){
            try{
            String codigo = txtCodigo.getText();
            String servicio=txtServicio.getText();
            double pago = Double.parseDouble(txtPagoAdmi.getText());
            String fecha = txtRFechaP3.getText()+"-"+txtRFechaP2.getText()+"-"+txtRFechaP1.getText();
            CallableStatement cst = con.prepareCall("{call usp_InsertarPagoAlumno(?,?,?,?,?)}");
            cst.setString(1,codigo);
            cst.setString(2,servicio);
            cst.setDouble(3,pago);
            cst.setString(4,fecha);
            cst.registerOutParameter(5, Types.CHAR);
            int rpta = cst.executeUpdate();
            String codigoPago = cst.getString(5);
            if(rpta==1){
               JOptionPane.showMessageDialog(this,"Se ha guardado correctamente","Informacion",JOptionPane.INFORMATION_MESSAGE);
               JOptionPane.showMessageDialog(this,"Codigo de pago: "+borrarespacios(codigoPago),"Informacion",JOptionPane.INFORMATION_MESSAGE);
            }
            cst.close();
         } catch (Exception ex) {
             ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,"ERROR AL GUARDAR","ERROR",JOptionPane.ERROR_MESSAGE);}
        }
        else{
            JOptionPane.showMessageDialog(this,"Ingrese Correctamente los datos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public String borrarespacios(String c){
        String cadena=null;
        boolean pos = false;
        int posicion=0;
        outerloop:
        for(int i=c.length()-1;i>=0;i--){
            if(c.charAt(i)!=' '){
                posicion=i+1;
                pos=true;
                break outerloop;
            }
        }
        if(pos)
            cadena=c.substring(0,posicion);
        else
            cadena=c;
        return cadena;
    }
    public boolean verificar(){
        boolean v=true;
        v=v&recorrer(txtCodigo.getText());
        v=v&recorrer(txtServicio.getText());
        v=v&recorrer(txtPagoAdmi.getText());
        v=v&recorrer(txtRFechaP1.getText());
        v=v&recorrer(txtRFechaP2.getText());
        v=v&recorrer(txtRFechaP3.getText());
        if(txtCodigo.getText().length()!=6){
            v=false;
        }
        if(txtServicio.getText().length()!=5){
            v=false;
        }
        if(cbxServicio.getSelectedIndex()==0){
            v=false;
        }
        return v;
    }
    public void limpiar(){
        DefaultTableModel asignacion = new DefaultTableModel();
        asignacion.addColumn("Codigo");
        asignacion.addColumn("Costo");
        asignacion.addColumn("Matricula");
        asignacion.addColumn("Ciclo");
        asignacion.addColumn("Fecha Inicio");
        asignacion.addColumn("Fecha Fin");
        this.tblServicios.setModel(asignacion);
    }
    public void mostrarAcademia(){
        DefaultTableModel asignacion = new DefaultTableModel();
        try {
            asignacion.addColumn("Codigo");
            asignacion.addColumn("Costo");
            asignacion.addColumn("Matricula");
            asignacion.addColumn("Ciclo");
            asignacion.addColumn("Fecha Inicio");
            asignacion.addColumn("Fecha Fin");
            CallableStatement cst = con.prepareCall("{call usp_ListarCicloAcademico}");
            ResultSet r=cst.executeQuery();
            while(r.next()){
                Object dato[] = new Object[6];
                for(int i=0;i<6;i++){
                    dato[i]=r.getString(i+1);
                }
            asignacion.addRow(dato);
            }
            this.tblServicios.setModel(asignacion);
            r.close();
            cst.close();
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al mostrar los datos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void mostrarAsesoria(){
        DefaultTableModel asignacion = new DefaultTableModel();
        try {
            asignacion.addColumn("Codigo");
            asignacion.addColumn("Costo");
            asignacion.addColumn("Matricula");
            asignacion.addColumn("Nivel Academico");
            CallableStatement cst = con.prepareCall("{call usp_ListarAsesoria}");
            ResultSet r=cst.executeQuery();
            while(r.next()){
                Object dato[] = new Object[4];
                for(int i=0;i<4;i++){
                    dato[i]=r.getString(i+1);
                }
            asignacion.addRow(dato);
            }
            this.tblServicios.setModel(asignacion);
            r.close();
            cst.close();
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al mostrar los datos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public boolean recorrer(String c){
        boolean v=true;
        int contador=0;
        if(c.length()==0){
            v=false;
        }
        else{
            for(int i=0;i<c.length();i++){
                if(c.charAt(i)==' '){
                    contador++;
                }
            }
            if(contador==c.length()){
                v=false;
            }
        }
        return v;
    }
     public void bloqueoLetras(java.awt.event.KeyEvent evt){
        char caracter = evt.getKeyChar();
      if((caracter < '0') ||(caracter > '9'))
          evt.consume();
    } 
     public int maximodia(int mes,int año){
        int maximo=0;
        switch(mes){
            case 0:
            case 2:
            case 4:
            case 6:
            case 7:
            case 9:
            case 11: maximo=31; break;
            case 1: if(año%4==0)
                      maximo=29;
                    else
                      maximo=28;
                    break;
            case 3:
            case 5:
            case 8:
            case 10:maximo=30;break;
        }
        return maximo;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar_PagoAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar_PagoAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar_PagoAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar_PagoAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Insertar_PagoAlum().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRFechaP;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPagoAdmi;
    private javax.swing.JTextField txtRFechaP1;
    private javax.swing.JTextField txtRFechaP2;
    private javax.swing.JTextField txtRFechaP3;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
