package academia;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class Modificar_Horarios extends javax.swing.JFrame {
   Connection con;
    int tabla;
    ImageIcon imagen = new ImageIcon("Icono.gif");
    Image icono = imagen.getImage();
    String codigoservicio;
    boolean seleccionar;
    public Modificar_Horarios() {
        initComponents();
        this.setTitle("Modificar Horarios");
        seleccionar=false;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:conexion");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR EN LA CONEXION","ERROR",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Insertar_Salones.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setIconImage(icono);
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnSeleccionar = new javax.swing.JButton();
        txtServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        cbxDias = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        btnSeleccionar.setBounds(530, 150, 110, 30);
        jLayeredPane1.add(btnSeleccionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtServicio.setEditable(false);
        txtServicio.setBounds(410, 150, 110, 30);
        jLayeredPane1.add(txtServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Servicio:");
        jLabel2.setBounds(340, 150, 70, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCursos);
        tblCursos.getColumnModel().getColumn(0).setResizable(false);
        tblCursos.getColumnModel().getColumn(1).setResizable(false);

        jScrollPane1.setBounds(30, 230, 320, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbxDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        cbxDias.setBounds(450, 230, 140, 30);
        jLayeredPane1.add(cbxDias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(430, 320, 69, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Salir");
        jButton2.setBounds(540, 320, 70, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/ModificarHorarios.png"))); // NOI18N
        jLabel1.setBounds(90, 0, 520, 80);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/Fondos/54.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 690, 430);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        seleccionar = true;         Seleccionar_Ciclo x = new Seleccionar_Ciclo();         x.setVisible(true);     }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(verificar()){
            eliminarCursoHorario();
        }
        else{
            JOptionPane.showMessageDialog(this,"Seleccione una fila, un Servicio y/o un dia");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       if(seleccionar){
            try {
                    String linea;
                    FileReader f = new FileReader("ActualizarServicio.txt");
                    BufferedReader b = new BufferedReader(f);
                    while((linea=b.readLine())!=null){
                        StringTokenizer t = new StringTokenizer(linea,",");
                        String boleano=t.nextToken();
                        if(Boolean.valueOf(boleano)){
                            codigoservicio=t.nextToken();
                            txtServicio.setText(t.nextToken());
                            seleccionar=false;
                            mostrarDatos();
                        }
                        else{
                            System.out.println(t.nextToken());
                            System.out.println(t.nextToken());
                        }
                    }
                    b.close();
           } catch (IOException ex) {}
            try {
                FileWriter f = new FileWriter("ActualizarServicio.txt");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al grabar el archivo","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowGainedFocus
    public void eliminarCursoHorario(){
        try{
           String servicio=txtServicio.getText();
           String codigocurso=String.valueOf(tblCursos.getValueAt(tblCursos.getSelectedRow(),0));
           String diasemana=null;
           switch(cbxDias.getSelectedIndex()){
               case 1:diasemana="2";break;
               case 2:diasemana="3";break;
               case 3:diasemana="4";break;
               case 4:diasemana="5";break;
               case 5:diasemana="6";break;
               case 6:diasemana="7";break;
               case 7:diasemana="1";break;
           }
           CallableStatement cst = con.prepareCall("{call usp_EliminarHOrariServicios(?,?,?)}");
           cst.setString(1,servicio);
           cst.setString(2,codigocurso);
           cst.setString(3,diasemana);
           int rpta = cst.executeUpdate();
           cst.close();
           if(rpta>=1){
               JOptionPane.showMessageDialog(this,"Se ha eliminado correctamente","Informacion",JOptionPane.INFORMATION_MESSAGE);
           }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error al guardar el Horario del curso","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void mostrarDatos(){
        DefaultTableModel Cursos = new DefaultTableModel();
        Cursos.addColumn("Codigo");
        Cursos.addColumn("Curso");
         if(recorrer(txtServicio.getText())){
             try {
                String codigo=txtServicio.getText();
                CallableStatement cst = con.prepareCall("{call usp_ListarCicloCurso(?)}");
                cst.setString(1,codigo);
                ResultSet r=cst.executeQuery();
                while(r.next()){
                    Object dato[] = new Object[2];
                    for(int i=0;i<2;i++){
                        dato[i]=r.getString(i+1);
                    }
                Cursos.addRow(dato);
                }
                r.close();
                cst.close();
            } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al mostrar los Cursos","Error",JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(Insertar_Salones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.tblCursos.setModel(Cursos);
    }
    public boolean verificar(){
        boolean v=true;
        v=v&recorrer(txtServicio.getText());
        if(tblCursos.getSelectedRow()==-1){
            v=false;
        }
        if(cbxDias.getSelectedIndex()==0){
            v=false;
        }
        return v;
    }
    public boolean recorrer(String c){
        boolean v=true;
        int contador=0;
        if(c.length()==0){
            v=false;
        }
        else{
            for(int i=0;i<c.length();i++){
                if(c.charAt(i)==' '){
                    contador++;
                }
            }
            if(contador==c.length()){
                v=false;
            }
        }
        return v;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Modificar_Horarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox cbxDias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
